
server:
  port: 8888
  servlet:
    context-path: /demo

spring:
  application:
    name: demo-rest-server

  jpa:
    open-in-view: true

datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
  username: sa
  password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

# define log-level's
logging:
  level:
    root: INFO
    com.example.demo: DEBUG

users:
  csv:
    filename: user.csv

management:
  endpoints:
    web:
      exposure:
        include: 'health,info,env'